exp_name: 'coords'
checkpoints: models
logs: logs
device: cuda
log_iterations: 20
wandb_entity: null
enable_progress_bar: True
dataset: coords

# Training parameters
lr: 1.0e-4
batch_size: 2
n_epochs: 1000
test_epochs: 20
n_stability_samples: 5
num_workers: 16
save_every_n_steps: 1000  # Save checkpoint every 1000 training steps
cache_mode: memory
cache_dir: cache

# EDM parameters
coord_scale_factor: 1
condition_time: True
tanh: True
norm_constant: 1.0
inv_sublayers: 1
diffusion_loss_type: l2
t_weight_power: 0
data_augmentation: False

# EDM diffusion parameters
diffusion_steps: 200
diffusion_noise_schedule: polynomial_2
diffusion_noise_precision: 0.00001

# GNN parameters
nf: 64
activation: silu
n_layers: 16
attention: True
normalization_factor: 1
normalize_factors: [1, 4, 1]
aggregation_method: 'sum'
normalization: batch_norm
low_memory: True
